### ISSUE TITLE
Can not log out

### ISSUE THREAD

**Issue by minogon** [dhaven/protonPass#11]
I can not log out on ProtonDriveSync release 0.1.4.  Windows 11 Pro 23H2

![Screenshot 2024-05-27 102542](https://github.com/dhaven/ProtonDriveSync/assets/67477340/6e9f184d-954a-4549-a150-0b87bffa0dbf)

Unable to refresh session: API response contains an error (10013) : Invalid refresh token

**Comment by dhaven** [comment]
Thanks for reporting the issue I will try to fix it asap. In the meantime you can manually delete the credentials by going to the credential manager window. Then scroll down until you find one called Keepass:ProtonDriveSyncPlugin and remove it (see screenshot).

![image](https://github.com/dhaven/ProtonDriveSync/assets/9165937/c268204a-0066-45c0-8398-dc4aef25e539)

**Comment by minogon** [comment]
> Thanks for reporting the issue I will try to fix it asap. In the meantime you can manually delete the credentials by going to the credential manager window. Then scroll down until you find one called Keepass:ProtonDriveSyncPlugin and remove it (see screenshot).
> 


I removed the plugin and removed the credentials Keepass:ProtonDriveSyncPlugin.

After I tried to log in with email. 
After I typed in the 6 numbers from my authentication app the ProtonDriveSyncPlugin generated error:

Unable to initialize user keys: Checksum mismatch at 0 of 20
ProtonDriveSync
   at ProtonDriveSync.StorageProvider.ProtonAPI.<InitUserKeys>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProtonDriveSync.StorageProvider.ProtonDriveStorageProvider.<Init>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProtonDriveSync.ProtonDriveSyncExt.<OnShowSetting>d__8.MoveNext()
Void MoveNext()

Now situation like as before - ProtonDriveSyncPlugin does not work

**Comment by askinner-1** [comment]
I'm having exactly the same problem described in the OP after changing my password for Proton Drive.

I can not log out on ProtonDriveSync release 0.1.4. Windows 11 Pro 25H2
Error message is identical.

I've removed the Windows credential manually, installed new KeePass 2.6 after uninstalling 2.59, and still get this error.
